version: '3'

services:
  nextjs-app:
    build:
      context: .
    container_name: nextjs-container
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
