import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
<<<<<<< HEAD
=======
import Navbar from "../components/Navbar";
>>>>>>> 35a076a97dba18968b00963ba025be6d7e90b0aa
=======
>>>>>>> parent of b623626 (session 1)

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Film List",
<<<<<<< HEAD
<<<<<<< HEAD
  description: "Generated by create next app",
=======
  description: "Nonton Anime lah kuy..",
>>>>>>> 35a076a97dba18968b00963ba025be6d7e90b0aa
=======
  description: "Generated by create next app",
>>>>>>> parent of b623626 (session 1)
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> parent of b623626 (session 1)
      <body className={inter.className}>
        <div>
          <h1>Ini ada di Layout, bisa di jadikan untuk navbar</h1>
        </div>
<<<<<<< HEAD
=======
      <body className={inter.className} suppressHydrationWarning={true}>
<<<<<<< HEAD
        <Navbar />
>>>>>>> 35a076a97dba18968b00963ba025be6d7e90b0aa
=======
        <Navbar className="" />
>>>>>>> ff25cdd (layput)
=======
>>>>>>> parent of b623626 (session 1)
        {children}
      </body>
    </html>
  );
}
